# Generated by Django 4.2.4 on 2023-08-26 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto_currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('number', models.BigIntegerField(db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CryptoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('number', models.BigIntegerField(db_index=True)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='crypto_currency.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crypto_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('crypto_currency', 'user')},
            },
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
