# Generated by Django 4.2.4 on 2023-08-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(choices=[('aban', 'Aban')], max_length=128)),
                ('logo', models.URLField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
